---
- name: set up dirs, including perms, owner, groups
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
    owner: bitnami
    group: daemon
  with_items:
    - /opt/bitnami/nginx/conf/server_blocks
    - /opt/bitnami/apps

- name: remove original wordpress directory
  become: yes
  ansible.builtin.file:
    path: /opt/bitnami/wordpress
    state: absent

- name: create symbolic link for apps dir
  ansible.builtin.file:
    src: /opt/bitnami/apps
    dest: /home/bitnami/apps
    state: link
  when: not ansible_check_mode

- name: remove orig nginx conf
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/bitnami/nginx/conf/server_blocks/default-https-server-block.conf
    - /opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf
    - /opt/bitnami/nginx/conf/server_blocks/wordpress-https-server-block.conf

# vim: ai et ts=2 sw=2 sts=2 nu
