---
- name: set up dirs, including perms, owner, groups
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
    owner: bitnami
    group: daemon
  with_items:
    - /opt/bitnami/nginx/conf/server_blocks
    - /opt/bitnami/apps
    - /opt/bitnami/apps/acme_validation/.well-known/acme-challenge
    - /opt/bitnami/apps/502
    - /opt/bitnami/apps/404

- name: remove original wordpress directory
  become: yes
  ansible.builtin.file:
    path: /opt/bitnami/wordpress
    state: absent

- name: create symbolic link for apps dir
  ansible.builtin.file:
    src: /opt/bitnami/apps
    dest: /home/bitnami/apps
    state: link
  when: not ansible_check_mode

- name: remove orig nginx conf
  become: yes
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf
    - /opt/bitnami/nginx/conf/server_blocks/wordpress-https-server-block.conf

- name: put back default-https-server-block
  become: yes
  ansible.builtin.copy:
    src: default-https-server-block.conf
    dest: /opt/bitnami/nginx/conf/server_blocks/default-https-server-block.conf
    #owner: bitnami
    #group: daemon
    #mode: '0664'

- name: set php-fpm.conf to tcp/ip not unix_sock
  become: yes
  template:
    src: php-fpm.conf.j2
    dest: /opt/bitnami/nginx/conf/bitnami/php-fpm.conf
    backup: yes
  notify:
    - Restart bitnami apps

- name: set www.conf to listen on tcp/ip not unix_sock
  become: yes
  template:
    src: www.conf.j2
    dest: /opt/bitnami/php/etc/php-fpm.d/www.conf
  notify:
    - Restart bitnami apps

- name: add 502 html page
  become: yes
  copy:
    src: 502.html
    dest: /opt/bitnami/apps/502
    mode: '0775'
    owner: bitnami
    group: daemon
  when: not ansible_check_mode

- name: add 404 html page
  become: yes
  copy:
    src: 404.html
    dest: /opt/bitnami/apps/404
    mode: '0775'
    owner: bitnami
    group: daemon
  when: not ansible_check_mode

- name: change 403 to 444 for remote phpmyadmin access
  become: yes
  ansible.builtin.lineinfile:
    path: /opt/bitnami/nginx/conf/bitnami/phpmyadmin.conf
    insertbefore: ' *return 403'
    line: '        return 444; # Drop'

# vim: ai et ts=2 sw=2 sts=2 nu
