---
- name: add secondary ip to running OS
  become: yes
  template:
    src: templates/secondary-ip.j2
    dest: /etc/network/interfaces.d/secondary-ip
    owner: root
    group: root
    mode: '0644'
  when: configure_2nd_ip is defined and configure_2nd_ip
  notify:
    - Restart networking

- name: install gpg key for zabbix repo
  # https://github.com/dj-wasabi/ansible-zabbix-agent/blob/master/tasks/Debian.yml
  become: yes
  apt_key:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    state: present
  when: install_zabbix is defined and install_zabbix

- name: install zabix repo
  become: yes
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb-src http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ansible_distribution_release }} main"
    - "deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian/ {{ansible_distribution_release }} main"
  when: install_zabbix is defined and install_zabbix

- name: do not install zabbix-server
  # No need for this, as mariadb is install in /opt by bitnami
  become: yes
  apt:
    name: zabbix-server-mysql
    update_cache: yes
    state: absent
  when: install_zabbix is defined and install_zabbix


# vim: ai et ts=2 sw=2 sts=2 nu
