---
- debug:
    msg: "{{ APPs }}"

- name: create app directories
  become: yes
  file:
    state: directory
    path: "/opt/bitnami/apps/{{ item.key }}"
    mode: '0775'
    owner: bitnami
    group: daemon
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable

- name: touch index.html for each app to check curl status
  become: yes
  changed_when: False
  file:
    state: touch
    path: "/opt/bitnami/apps/{{ item.key }}/index.html"
    mode: '0664'
    owner: bitnami
    group: daemon
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable

- name: create simple nginx config
  become: yes
  template:
    src: templates/simple.conf.j2
    dest: "/opt/bitnami/nginx/conf/server_blocks/{{ item.key }}.conf"
    owner: bitnami
    group: daemon
    mode: '0664'
  loop: "{{ APPs | dict2items }}"
  when: not item.value.redirect_elsewhere and item.value.enable
  notify:
    - Restart bitnami apps

- name: create redirect nginx config
  become: yes
  template:
    src: templates/redirect.conf.j2
    dest: "/opt/bitnami/nginx/conf/server_blocks/{{ item.key }}.conf"
    owner: bitnami
    group: daemon
    mode: '0664'
  loop: "{{ APPs | dict2items }}"
  when: item.value.redirect_elsewhere and item.value.enable
  notify:
    - Restart bitnami apps

# vim: ai et ts=2 sw=2 sts=2 nu
