---
- debug:
    msg: "{{ APPs }}"

- name: create app directories
  become: yes
  file:
    state: directory
    path: "/opt/bitnami/apps/{{ item.key }}"
    mode: '0775'
    owner: bitnami
    group: daemon
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable

- name: touch index.html for each app to check curl status
  become: yes
  changed_when: False
  file:
    state: touch
    path: "/opt/bitnami/apps/{{ item.key }}/index.html"
    mode: '0664'
    owner: bitnami
    group: daemon
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable

- name: create simple nginx config
  become: yes
  template:
    src: templates/simple.conf.j2
    dest: "/opt/bitnami/nginx/conf/server_blocks/{{ item.key }}.conf"
    owner: bitnami
    group: daemon
    mode: '0664'
  loop: "{{ APPs | dict2items }}"
  when: not item.value.redirect_elsewhere and item.value.enable
  notify:
    - Restart bitnami apps

- name: create redirect nginx config
  become: yes
  template:
    src: templates/redirect.conf.j2
    dest: "/opt/bitnami/nginx/conf/server_blocks/{{ item.key }}.conf"
    owner: bitnami
    group: daemon
    mode: '0664'
  loop: "{{ APPs | dict2items }}"
  when: item.value.redirect_elsewhere and item.value.enable
  notify:
    - Restart bitnami apps

- name: set cron shell
  cron:
    name: SHELL
    env: yes
    value: /usr/bin/bash

- name: install lego cron renew
  cron:
    name: "{{ item.key }} lego renew"
    hour: "{{ item.value.lego_cron_hour }}"
    minute: "{{ item.value.lego_cron_min }}"
    weekday: "{{ item.value.lego_cron_weekday }}"
    job: "sudo /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencrypt/ --tls --domains {{ item.key }}  --email '{{ item.value.lego_email }}' renew --renew-hook '/opt/bitnami/nginx/sbin/nginx -s reload' >/dev/null 2>&1"
    state: present
    disabled: "{{ item.value.lego_cron_disable }}"
  loop: "{{ APPs | dict2items }}"
  when: item.value.enable and item.value.lego_cron_install is defined and item.value.lego_cron_install

- name: create letsencrypt directory
  become: yes
  file:
    state: directory
    path: "/opt/bitnami/letsencrypt"
    mode: "0755"
    owner: root
    group: root
  when: install_lego

- name: remove tmp lego glob files
  become: yes
  file:
    state: absent
    path: "{{ item }}"
  with_fileglob:
    - '/tmp/lego*'
  when: install_lego

- name: install lego binary if it does not exist
  become: yes
  script: scripts/install_lego.sh
  args:
    creates: /opt/bitnami/letsencrypt/lego
  when: install_lego


# vim: ai et ts=2 sw=2 sts=2 nu
