---
- name: display private_vars.yaml
  debug:
    msg: "{{ APPs }}"

- name: create app directories
  become: yes
  file:
    state: directory
    path: "/opt/bitnami/apps/{{ item.key }}"
    mode: '0775'
    owner: bitnami
    group: daemon
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable

- name: does a index.php file exist
  ansible.builtin.stat:
    path: "/opt/bitnami/apps/{{ item.key }}/index.php"
  register: index_php_stat
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable

- name: Create and Add items to dictionary
  set_fact: 
      index_php_present: "{{ index_php_present | default({}) | combine ({ item.item.key : item.stat.exists }) }}"
  loop: "{{ index_php_stat.results }}"

- name: Display the Dictionary
  debug: var=index_php_present

- name: touch index.html unless index.php exists, so user can safely remove index.html
  become: yes
  changed_when: False
  file:
    state: touch
    path: "/opt/bitnami/apps/{{ item.key }}/index.html"
    mode: '0664'
    owner: bitnami
    group: daemon
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable and not index_php_present[item.key]

- name: debug index_php_present var
  debug:
    msg: "{{ item.key }} - {{ index_php_present[item.key] }}"
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable

- name: create simple nginx config
  become: yes
  template:
    src: templates/simple.conf.j2
    dest: "/opt/bitnami/nginx/conf/server_blocks/{{ item.key }}.conf"
    owner: bitnami
    group: daemon
    mode: '0664'
  loop: "{{ APPs | dict2items }}"
  when: not item.value.redirect_elsewhere and item.value.enable
  notify:
    - Restart bitnami apps

- name: create redirect nginx config
  become: yes
  template:
    src: templates/redirect.conf.j2
    dest: "/opt/bitnami/nginx/conf/server_blocks/{{ item.key }}.conf"
    owner: bitnami
    group: daemon
    mode: '0664'
  loop: "{{ APPs | dict2items }}"
  when: item.value.redirect_elsewhere and item.value.enable
  notify:
    - Restart bitnami apps

- name: set cron shell
  cron:
    name: SHELL
    env: yes
    value: /usr/bin/bash

- name: install lego cron renew
  cron:
    name: "{{ item.key }} lego renew"
    hour: "{{ item.value.lego_cron_hour }}"
    minute: "{{ item.value.lego_cron_min }}"
    weekday: "{{ item.value.lego_cron_weekday }}"
    job: "sudo /opt/bitnami/letsencrypt/lego --path /opt/bitnami/letsencrypt/ --tls --domains {{ item.key }}  --email '{{ item.value.lego_email }}' renew --renew-hook '/opt/bitnami/nginx/sbin/nginx -s reload' >/dev/null 2>&1"
    state: present
    disabled: "{{ item.value.lego_cron_disable }}"
  loop: "{{ APPs | dict2items }}"
  when: item.value.enable and item.value.lego_cron_install is defined and item.value.lego_cron_install

- name: install wp_cron 
  become: yes
  cron:
    name: "{{ item.key }} wp_cron"
    minute: "{{ item.value.wp_cron_min }}"
    job: 'su daemon -s /bin/sh -c "cd /opt/bitnami/apps/{{ item.key }}; /opt/bitnami/php/bin/php -q wp-cron.php"'
    state: present
    disabled: "{{ item.value.wp_cron_disable }}"
  loop: "{{ APPs | dict2items }}"
  when: item.value.enable and item.value.wp_cron_install is defined and item.value.wp_cron_install

- name: create letsencrypt directory
  become: yes
  file:
    state: directory
    path: "/opt/bitnami/letsencrypt"
    mode: "0750"
    owner: root
    group: root
  when: install_lego

- name: confirm certs directory permissions
  become: yes
  file:
    state: directory
    path: /opt/bitnami/nginx/conf/bitnami/certs
    mode: "0600"
    owner: root
    group: root

- name: find exisitng lego crt and key file
  become: yes
  register: cert_files
  find:
    file_type: file
    path: /opt/bitnami/letsencrypt/certificates
    patterns: '*.crt,*.key'
    excludes: '*issuer*'

- name: display cert files
  debug:
    var: cert_files

- name: Create symlinks to /opt/bitnami/letsencrypt/certificates
  become: yes
  file:
    src: "{{ item.path }}"
    path: "/opt/bitnami/nginx/conf/bitnami/certs/{{ item.path | basename }}"
    state: link
  with_items: "{{ cert_files.files }}"

- name: remove tmp lego glob files
  become: yes
  file:
    state: absent
    path: "{{ item }}"
  with_fileglob:
    - '/tmp/lego*'
  when: install_lego

- name: install lego binary if it does not exist
  become: yes
  script: scripts/install_lego.sh
  args:
    creates: /opt/bitnami/letsencrypt/lego
  when: install_lego

- name: update php.ini with tz for zabbix
  become: yes
  lineinfile:
    path: /opt/bitnami/php/etc/php.ini
    regexp: '^date.timezone ='
    line: 'date.timezone = America/New_York'
  notify:
    - Restart bitnami apps
  when: install_zabbix is defined and install_zabbix

- name: create databases for ea app
  mysql_db:
    config_file: /opt/bitnami/mariadb/conf/my.cnf
    state: present
    name: "{{ item.value.database_name }}"
    collation: utf8_bin
    encoding: utf8
    login_password: "{{ MariaDB_Root_Password }}"
    login_user: root
  loop: "{{ APPs | dict2items }}"
  when: item.value.enable and item.value.database_name is defined

- name: Create user with password, all database privileges and WITH GRANT OPTION for each app
  community.mysql.mysql_user:
    login_password: "{{ MariaDB_Root_Password }}"
    login_user: root
    state: present
    name: "{{ item.value.database_user }}"
    password: "{{ item.value.database_password }}"
    priv: "{{ item.value.database_name }}.*:ALL,GRANT"
  loop: "{{ APPs | dict2items }}"
  when: item.value.enable and item.value.database_user is defined and item.value.database_password is defined


# vim: ai et ts=2 sw=2 sts=2 nu
