---
- name: install poohbear default conf
  become: yes
  template:
    src: templates/poohbear.conf.j2
    dest: /opt/bitnami/nginx/conf/server_blocks/poohbear.conf
    owner: bitnami
    group: daemon
    mode: '0664'
  when: install_poohbear_default
  notify:
    - Restart bitnami

- name: install poohbear app dir
  become: yes
  file:
    state: directory
    path: /opt/bitnami/apps/poohbear
    owner: bitnami
    group: daemon
    mode: '0775'
  when: install_poohbear_default
  notify:
    - Restart bitnami

- name: install poohhbear app index.php
  become: yes
  copy:
    src: files/index.php
    dest: /opt/bitnami/apps/poohbear/index.php
    owner: bitnami
    group: daemon
    mode: '0664'
  when: install_poohbear_default
  notify:
    - Restart bitnami

- name: remove poohbear default conf
  become: yes
  file:
    state: absent
    dest: "{{ item }}"
  when: not install_poohbear_default
  notify:
    - Restart bitnami
  loop:
    - /opt/bitnami/nginx/conf/server_blocks/poohbear.conf
    - /opt/bitnami/apps/poohbear


# vim: ai et ts=2 sw=2 sts=2 nu
