---
- name: check app dir and files owner and group in ansible_check_mode
  become: yes
  command: find /opt/bitnami/apps/{{ item.key }} ! \( -user bitnami -group daemon \) -print
  args:
    warn: false
  changed_when: False
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable
  register: need_chown_updating
  check_mode: no

- name: display which app dir and files need chown updating
  debug:
    msg: "Needs chown updating: {{ item.stdout_lines }}"
  with_items: "{{ need_chown_updating.results }}"
  when: item.stdout is defined and item.stdout and ansible_check_mode
  #
#
#- name: check file permissions
#  become: yes
#  command: find /opt/bitnami/apps/{{ item.key }} -type f -exec chmod 0664 {} \;
#  args:
#    warn: false
#  changed_when: False
#  loop: "{{ APPs | dict2items }}"
#  loop_control:
#    label: "{{ item.key }}"
#  when: item.value.enable
#
#- name: check directory permissions
#  become: yes
#  command: find /opt/bitnami/apps/{{ item.key }} -type d -exec chmod 0775 {} \;
#  args:
#    warn: false
#  changed_when: False
#  loop: "{{ APPs | dict2items }}"
#  loop_control:
#    label: "{{ item.key }}"
#  when: item.value.enable
#

- name: check wp-config permissions in ansible_check_mode
  become: yes
  command: find /opt/bitnami/apps/{{ item.key }} -maxdepth 1 -type f -name wp-config.php ! -perm 0440 -print
  args:
    warn: false
  changed_when: False
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable
  register: need_wp_config_chmod_updating
  check_mode: no

- name: display which wp-config.php need chmod updating
  debug:
    msg: "Needs chmod updating: {{ item.stdout }}"
  with_items: "{{ need_wp_config_chmod_updating.results }}"
  when: item.stdout is defined and item.stdout and ansible_check_mode

- name: update wp-config permissions if needed
  become: yes
  command: find /opt/bitnami/apps/{{ item.key }} -maxdepth 1 -type f -name wp-config.php ! -perm 0440 -exec chmod 0440 {} \; -print
  args:
    warn: false
  changed_when: False
  loop: "{{ APPs | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value.enable
  register: wp_config_chmod_changed

- name: display which wp-config.php chmod changed
  debug:
    msg: "chmod updated: {{ item.stdout }}"
  with_items: "{{ wp_config_chmod_changed.results }}"
  when: item.stdout is defined and item.stdout and not ansible_check_mode

###### The commented tasks are too intensive for large directories and fail
#- name: register dirs
#  become: yes
#  ansible.builtin.find:
#    path: /opt/bitnami/apps
#    file_type: directory
#    recurse: yes
#  register: find_dir_result
#
#- name: set dir permissions
#  become: yes
#  file:
#    path: "{{ item.path }}"
#    owner: bitnami
#    group: daemon
#    mode: '0775'
#  with_items: "{{ find_dir_result.files }}"
#
#- name: register files
#  become: yes
#  ansible.builtin.find:
#    path: /opt/bitnami/apps
#    file_type: file
#    exclude: wp-config.php
#    recurse: yes
#  register: find_files_result
#
#- name: set file permissions
#  become: yes
#  file:
#    path: "{{ item.path }}"
#    owner: bitnami
#    group: daemon
#    mode: '0664'
#  with_items: "{{ find_files_result.files }}"
#
#- name: register wp_config
#  become: yes
#  ansible.builtin.find:
#    path: /opt/bitnami/apps
#    file_type: file
#    patterns: '*wp-config.php'
#    recurse: yes
#    use_regex: no
#  register: find_wp_config
#
#- name: set wp_config.php permissions
#  become: yes
#  file:
#    path: "{{ item.path }}"
#    owner: bitnami
#    group: daemon
#    mode: '0440'
#  with_items: "{{ find_wp_config.files }}"
#
#
# vim: ai et ts=4 sw=4 sts=4 nu
