---

- hosts: nginx_hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
  connection: local
  roles:
    - prep_work
    - pre_app_nginx_configuration
    - setup_db
    - install_poohbear_default
    - check_apps_permissions
    - check_nginx_conf_permissions

# vim: ai et ts=2 sw=2 sts=2 nu
