---
- hosts: nginx_hosts
  vars:
    ansible_python_interpreter: /usr/bin/python3
    HOME: "{{ lookup('env', 'HOME') }}"
  vars_files:
    - /opt/bitnami/apps/configuration/private_vars.yaml
  connection: local
  roles:
    - role: prep_work
      tags: [prep_work]
    - role: pre_app_nginx_configuration
      tags: [pre_app_nginx]
    - role: setup_db
      tags: [setup_db]
    - role: install_poohbear_default
      tags: [install_poohbear]
    - role: install_apps
      tags: [install_apps]
    - role: check_apps_permissions
      tags: [app_perms]
    - role: check_nginx_conf_permissions
      tags: [check_nginx_conf]

# vim: ai et ts=2 sw=2 sts=2 nu
